apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - servicemonitor-vllm.yaml
configMapGenerator:
  - name: llm-inference-dashboard
    files:
      - llm-inference.json=dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
