grafana:
  enabled: true
  defaultDashboardsEnabled: false
  service:
    type: ClusterIP
  persistence:
    enabled: false
  admin:
    existingSecret: monitoring-grafana

prometheus:
  enabled: true
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 24h
    retentionSize: 2GB
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: false

kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
