grafana:
  enabled: true
  defaultDashboardsEnabled: false
  service:
    type: ClusterIP
  persistence:
    enabled: false
  admin:
    existingSecret: monitoring-grafana
  tolerations:
    - key: mlops.local/gpu
      operator: Equal
      value: dedicated
      effect: NoSchedule

prometheus:
  enabled: true
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 24h
    retentionSize: 2GB
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    tolerations:
      - key: mlops.local/gpu
        operator: Equal
        value: dedicated
        effect: NoSchedule

prometheusOperator:
  tolerations:
    - key: mlops.local/gpu
      operator: Equal
      value: dedicated
      effect: NoSchedule
  admissionWebhooks:
    patch:
      tolerations:
        - key: mlops.local/gpu
          operator: Equal
          value: dedicated
          effect: NoSchedule

kube-state-metrics:
  tolerations:
    - key: mlops.local/gpu
      operator: Equal
      value: dedicated
      effect: NoSchedule

prometheus-node-exporter:
  tolerations:
    - key: mlops.local/gpu
      operator: Equal
      value: dedicated
      effect: NoSchedule

alertmanager:
  enabled: false

kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
