grafana:
  enabled: true
  defaultDashboardsEnabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
  service:
    type: ClusterIP
  persistence:
    enabled: false
  admin:
    existingSecret: monitoring-grafana
  tolerations:
    - key: mlops.local/gpu
      operator: Equal
      value: dedicated
      effect: NoSchedule

prometheus:
  enabled: true
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 24h
    retentionSize: 2GB
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: true
    tolerations:
      - key: mlops.local/gpu
        operator: Equal
        value: dedicated
        effect: NoSchedule

prometheusOperator:
  tolerations:
    - key: mlops.local/gpu
      operator: Equal
      value: dedicated
      effect: NoSchedule
  admissionWebhooks:
    enabled: false

alertmanager:
  enabled: false

defaultRules:
  create: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
