apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "llm-inference.fullname" . }}-model-cache
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "llm-inference.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
