apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-inference.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "llm-inference.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "llm-inference.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
