apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-inference.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "llm-inference.labels" . | nindent 4 }}
automountServiceAccountToken: false
