apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workflow-serviceaccount.json
  - workflow-role.json
  - workflow-rolebinding.json
  - cpu-synthetic-release-v1.json
labels:
  - pairs:
      app.kubernetes.io/part-of: mlops-release-lab
