apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.json
  - pvc.json
  - deployment.json
  - service.json
labels:
  - pairs:
      app.kubernetes.io/part-of: mlops-release-lab
